apiVersion: v1
kind: Service
metadata:
  name: journit-service
spec:
  type: LoadBalancer          # Docker Desktop automatically maps LoadBalancers to localhost!
  selector:
    app: journit-app          # MUST match the exact matchLabels defined in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80                # The stable port internal cluster applications use to talk to this service
      targetPort: 80          # The container port on the Pod traffic is redirected to
      nodePort: 30080         # Opens port 30080 externally. Access via http://<Node_IP>:30080